function jacobian_dx_wrt_u = autoGen_jac_dxu_B_com(px,py,pz,vx,vy,vz,qw,qx,qy,qz,wx,wy,wz,u1,u2,u3,u4)
%AUTOGEN_JAC_DXU_B_COM
%    JACOBIAN_DX_WRT_U = AUTOGEN_JAC_DXU_B_COM(PX,PY,PZ,VX,VY,VZ,QW,QX,QY,QZ,WX,WY,WZ,U1,U2,U3,U4)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    29-Oct-2019 09:02:26

t2 = qw.^2;
t3 = qx.^2;
t4 = qy.^2;
t5 = qz.^2;
t6 = sqrt(2.0);
t11 = qw.*qx.*(1.0e+2./4.1e+1);
t12 = qw.*qy.*(1.0e+2./4.1e+1);
t13 = qx.*qz.*(1.0e+2./4.1e+1);
t14 = qy.*qz.*(1.0e+2./4.1e+1);
t7 = t2.*(5.0e+1./4.1e+1);
t8 = t3.*(5.0e+1./4.1e+1);
t9 = t4.*(5.0e+1./4.1e+1);
t10 = t5.*(5.0e+1./4.1e+1);
t17 = -t11;
t18 = t12+t13;
t21 = t6.*1.706059859628644e+1;
t22 = t6.*1.706059859628645e+1;
t23 = t6.*1.706059859628644e+1;
t24 = t6.*1.706059859628645e+1;
t15 = -t8;
t16 = -t9;
t19 = t14+t17;
t20 = t7+t10+t15+t16;
jacobian_dx_wrt_u = reshape([0.0,0.0,0.0,t18,t19,t20,0.0,0.0,0.0,0.0,t24,-t21,1.964594085393047,0.0,0.0,0.0,t18,t19,t20,0.0,0.0,0.0,0.0,t22,t23,-1.964594085393047,0.0,0.0,0.0,t18,t19,t20,0.0,0.0,0.0,0.0,-t24,t21,1.964594085393047,0.0,0.0,0.0,t18,t19,t20,0.0,0.0,0.0,0.0,-t22,-t23,-1.964594085393047],[13,4]);
